---
title: "Fisheries Management Group"
author: "[Alex Smith](http://ucsb-bren.github.io/env-info/students/alxsmith.html), [Caio Faro](http://ucsb-bren.github.io/env-info/students/caio-faro.html), [Juliana Herrera](http://ucsb-bren.github.io/env-info/students/julianaherrera.html)"

date: "January 22, 2016"
output: html_document
---

# Types of data

We will use a time series data of landings in Costa Rica collected by INCOPESCA, the governmental institution in charge of fisheries management in the country. The data set contains different species and groups of species caught in the country, and it's divided into regions. For the purpose of our project, we will focus only in the Guanacaste region, specifically on snappers.

The data is in an excel file of monthly catches from 1990 until 2013

# Data and metadata standards



# Policies for access and sharing

Data will be available with expressed permissions from the C R Seafood group. 


*It is the responsibility of researchers and organizations to make results, data, derived data products, and collections available to the research community in a timely manner and at a reasonable cost. In the interest of full and open access, data should be provided at the lowest possible cost to researchers and educators. This cost should, as a first principle, be no more than the marginal cost of filling a specific user request. Data may be made available for secondary use through submission to a national data center, publication in a widely available scientific journal, book or website, through the institutional archives that are standard for a particular discipline (e.g. IRIS for seismological data, UNAVCO for GP data), or through other EAR-specified repositories. Data inventories should be published or entered into a public database periodically and when there is a significant change in type, location or frequency of such observations. Principal Investigators working in coordinated programs may establish (in consultation with other funding agencies and NSF) more stringent data submission procedures.*




# Policies and provisions for re-use, re-distribution

<<<<<<< HEAD
Describe policies surrounding the re-use of your data – the EAR division is specifically interested in how soon you will make your data available. If you will not be making the data available for re-use immediately, explain why. Remember that EAR specifies that you must make your data available no later than two years after your research is complete. If there are other policy issues regarding data access and re-use (ethical or privacy issues, for instance) elaborate on them here. Consider these questions:

When will you make the data available?
Does the original data collector/creator/principal investigator retain the right to use the data before opening it up to wider use?
Will any permission restrictions need to be placed on the data?
How long will the original data collector/creator/principal investigator retain the right to use the data before making them available for wider distribution?
Are there any embargo periods for political/commercial/patent reasons? If so, give details.
Are there ethical and privacy issues? If so, how will these be resolved?
What have you done to comply with your obligations in your IRB Protocol?
Who will hold the intellectual property rights to the data and how might this affect data access?
What and who are the intended or foreseeable uses / users of the data?
Additional help for: University of California, Santa Barbara

EZID, a service from the University of California Curation Center, facilitates data sharing, data reuse, data citation, and data attribution, and creates Digital Object Identifiers (DOI) for research data.
The Merritt Repository can restrict access to data to just the depositor or to a research group, or make data publicly available. Research data and records will be maintained for as long as they are of continuing value to the researchers and project collaborators. Data will be retained subject to the University of California retention policy.
If you’d like more information about how these tools can meet your data management requirements, contact uc3@ucop.edu
=======
For those programs in which selected principle investigators have initial periods of exclusive data use, data should be made openly available as soon as possible, but no later than two (2) years after the data were collected. This period may be extended under exceptional circumstances, but only by agreement between the Principal Investigator and the National Science Foundation. For continuing observations or for long-term (multi-year) projects, data are to be made public annually.
>>>>>>> a9c5b1cbbfe0a5fca3940b9cae8331e6b428e64a


# Plans for archiving and preservation of access

Describe your long-term strategy for archiving and preserving your data. EAR encourages PIs to submit data to an “EAR-specified” repository. Consider the following:

What is the long-term strategy for maintaining, curating and archiving the data?
Which archive/repository/database have you identified as a place to deposit data?
What procedures does your intended long-term data storage facility have in place for preservation and backup?
How long will/should data be kept beyond the life of the project?
What data will be preserved for the long-term?
What transformations will be necessary to prepare data for preservation / data sharing?
What metadata/ documentation will be submitted alongside the data or created on deposit/ transformation in order to make the data reusable?
What related information will be deposited?

```{r}
library(readxl)
library(plyr) 
library(dplyr) 
library(tidyr)
library(ggplot2)

snapper <- read_excel('snappermeans.xlsx')
  
catch <- snapper %>%
  group_by(Year) %>%
  summarise(sum = sum(catch, na.rm = TRUE)) %>%
  ggplot(aes(Year, sum)) +
  theme_bw() +
  geom_point(alpha = 1, color = 'orange', size = 5)
catch
```

