---
title: "Exploring Costa Rican Snapper Landings Through Time"
author: 'Fisheries Management Group: Caio Faro, Juliana Herrera, Alex Smith'
date: "March 11, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction - Fisheries Management

Seafood is the main source of animal protein for many developing and transition countries in the world. Additionally, the demand of this kind of food in developed countries have been expanding in a way that can't be met by their own fisheires production. These factors combined have resulted in a increased fishing effort around the globe, especially in developing countries (Swartz et al. 2010), that has led to populations declines in several of the main fisheries in the world.



### Costa Rica

Costa Rica is a small Central American country with a land area of approximately 51,100 km2 and coastlines on both the Pacific Ocean and Caribbean Sea (Herrera-Ulloa et al. 2011). The Pacific coastline of Costa Rica spans 1,016 km, with two large peninsulas, several bays and gulfs, many small islands, and a continental shelf area of approximately 15,600 km2 (Villalobos 1982). The Caribbean coastline is much shorter (212 km) and largely linear, with only two small islands and a continental shelf area of only 2,400 km2 (Villalobos 1982). In comparisson to the small terrestrial size, Costa Rica has a disproportionately large EEZ (589,000 km2) on the Pacific coast, due to the position of Cocos Island 644 km to the Southwest of the country.

It is estimated that more than 14,000 fishers live on the coasts and islands of Costa Rica, many of whom are living in impoverished conditions due to deterioration of the fisheries, poor monetary compensation and labor conditions, weak infrastructure of the artisanal sector, and a market with an industrial bias (FECOP 2013). About 95% of Costa Rica’s fishing fleet operates in the Pacific Ocean, which can be divided into four regions (Palacios 2007): Guanacaste, Gulf of Nicoya, Central Pacific, and South Pacific (Figure apple). On the Caribbean coast, most fishing activity is centered around Limón, though there are also many small landing sites on the southern coast near Puerto Viejo (Herrera-Ulloa et al. 2011).  Between 75% and 80% of all landings in Costa Rica come from the artisanal fleet, which encompasses boats with a very wide range of characteristics.  


### Objectives


### Data

We used a time series data of landings in Costa Rica from 1990 until 2013 collected by INCOPESCA, the governmental institution in charge of fisheries management in the country. The data set contains different species and groups of species caught in the country, and it's divided into regions. For the purpose of our project, we focused in Guanacaste region, specifically with pargo seda and pargo.  The data is in an excel file, separated by year. 

## Methods

Data reading, wrangling, visualization and management were developed with packages, functions and tools covered in the Environmental Informatics course from the Bren School of Environmental Science & Management.

Topics on this course included  basic computing environment (hardware and operating systems); programming language concepts; program design; data organization; software tools; generic analytical techniques (relational algebra, graphics & visualization, etc.); and specific characteristics of environmental information.

## Results - Graphs

## Discussion

### Our project

### Informatics

## References

Herrera-Ulloa, A., Villalobos-Chacón, L., Palacios-Villegas, J., Viquez-Portuguéz, R. and Oro-Marcos, G. 2011. Coastal fisheries of Costa Rica. In S. Salas, R. Chuenpagdee, A. Charles and J.C. Seijo (eds). Coastal fisheries of Latin America and the Caribbean. FAO Fisheries and Aquaculture Technical Paper. No. 544. Rome, FAO. pp. 137-153.

Swartz W, Sala E, Tracey S, Watson R, Pauly D (2010) The Spatial Expansion and Ecological Footprint of Fisheries (1950 to Present). PLoS ONE 5(12): e15143. doi:10.1371/journal.pone.0015143

Villalobos C. 1982. Animales y plantas comunes de las costas de Costa Rica. EUNED. Costa Rica.

